### ISSUE TITLE
problem with raspi 5

### ISSUE THREAD

**Issue by oldfartradioman** [300bps/hellopi#1]
Pi 5 not showing up but responding to ping on local wlan.

**Comment by 300bps** [comment]
There are a couple things to try to narrow down this issue:
* Make sure you are powering-up the RPi 5 on the LAN only **AFTER** you have hellopi running.  It can take 30 or more seconds after powering-up before the IP address is seen and printed.
* Try using hellopi with the '-a' flag to see ALL (not just Pis) devices that enumerate on the WAN. Then power-cycle the Pi 5 on the same LAN and see if it shows up.
* Provide the MAC address of the RPi5 (ifconfig command).  I can check it to see if they have added additional ranges of MAC addresses.

**Comment by 300bps** [comment]
Newest version (1.0.1) updates the list of OUI MAC address prefixes to include new ones aquired by RPi Foundation since this program was initially released.  This should address and correct the reported issue.
